baseurl = "https://ricardoheath.co.uk"
languageCode = "en"
title = "Ricardo Heath"
theme = "Hucore"
publishDir = "public"
enableGitInfo = true
ignoreLogs =['warning-goldmark-raw-html']
summaryLength = 100

[markup.goldmark.renderer]
unsafe= true

[frontmatter]
lastmod =['modified', ':fileModTime']

[pagination]
pagerSize = 20

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Ricardo Heath's Portfolio"
keywords = ["C++", "Gamedev", "Programming", "Portfolio", "Webdev"]
displayauthor = true
author = "Ricardo Heath"
sharingicons = false

[params.highlight]
theme = "atom-one-dark"
languages = ["cpp"]

[[params.social]]
url = "https://github.com/zephilinox"
fa_icon = "fa-brands fa-github"

[[params.social]]
url = "https://bsky.app/profile/zeph.wtf"
fa_icon = "fa-brands fa-bluesky"

[[params.social]]
url = "https://www.linkedin.com/in/ricardo-heath/"
fa_icon = "fa-brands fa-linkedin"
