# Site settings
baseurl = "https://zephilinox.github.io/"
languageCode = "en-us"
title = "Ricardo Heath's Portfolio"
theme = "freelancer"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Ricardo Heath"
    description = "Student studying Games Development at UWE"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Ricardo Heath's Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Ricardo Heath"
        subtitle = "Blogger - Programmer - Student"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "I'm a student studying games development looking to gain industry experience. I'm particularly interested in engine architecture and gameplay programming."
        right = "I love creating technical bits of code to understand how it all fits together to produce a game. Check out my github or resume below for more information."

        [params.about.button]
            text = "Resume"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Bristol", "United Kingdom"]

        [params.footer.social]
            title = "Contact"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/zephilinox"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/zephilinox"
				
            [[params.footer.social.networks]]
                icon = "fa-reddit"
                link=  "//reddit.com/u/zephilinox"
				
            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/in/ricardo-h-9805378a"
				
            [[params.footer.social.networks]]
                icon = "fa-envelope-o"
                link=  "mailto:rmfhzx@gmail.com"

        [params.footer.credits]
            title = "Credits"
            text = "Freelancer is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
