baseurl = "https://ricardoheath.co.uk"
languageCode = "en"
title = "Ricardo Heath"
theme = "Hucore"
disqusShortname = ""
googleAnalytics = "UA-118667261-1"
publishDir = "public"
enableGitInfo = true
Paginate = 20

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Ricardo Heath's Portfolio"
keywords = ["C++", "Gamedev", "Programming", "Portfolio"]
displayauthor = true
author = "Ricardo Heath"
sharingicons = false

[params.highlight]
theme = "atom-one-dark"
languages = ["cpp"]

[[params.social]]
url = "https://github.com/zephilinox"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/zephilinox"
fa_icon = "fa-twitter"